name: CI devops 2025

on:
  push:
    branches:
      - master
      - develop

  pull_request:

jobs:

  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and test with Maven
        run: mvn clean verify --file ./backend/simpleapi/pom.xml


  build-backend:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/simpleapi
          push: false
          tags: tp-devops-simple-api:latest
          outputs: type=oci,dest=/tmp/backend.tar

      - name: Upload backend image
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: /tmp/backend.tar


  build-database:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: false
          tags: tp-devops-database:latest
          outputs: type=oci,dest=/tmp/database.tar

      - name: Upload database image
        uses: actions/upload-artifact@v4
        with:
          name: database-image
          path: /tmp/database.tar


  build-httpd:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          push: false
          tags: tp-devops-httpd:latest
          outputs: type=oci,dest=/tmp/httpd.tar

      - name: Upload httpd image
        uses: actions/upload-artifact@v4
        with:
          name: httpd-image
          path: /tmp/httpd.tar